server:
  port: 80

spring:
  application:
    name: hostmonitor_web_80
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'

