server:
  port: 9000

spring:
  application:
    name: hostmonitor-data-collector-9000
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.105.123.116:3306/StorageDeviceMonitor?useSSL=false&useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC
    username: root
    password: b511
management:
  endpoints:
    web:
      exposure:
        include: '*'
