server:
  port: 80


spring:
  application:
    name: hostmonitor-web
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'

service-url:
  data_collector_service: http://hostmonitor-data-collector  #http://localhost:9000  #
  web_service: http://hostmonitor-web