server:
  port: 80
spring:
  application:
    name: hostmonitor-web
management:
  endpoints:
    web:
      exposure:
        include: '*'

service-url:
  data_collector_service: http://localhost:9001
  web_service: http://hostmonitor-web
